[meta]
name     = "AK Hints"
author   = "XertroV"
category = "Race"
version  = "0.1.4"
siteid   = 449

[script]
#__DEFINES__
dependencies = ["VehicleState"]
exports = ["Ak_Exports.as"]
module = "AkHints"
